### ISSUE TITLE
Self-hosted packages in pubspec.yaml aren't supported.

### ISSUE THREAD

**Issue by dustinlessard-wf** [thosakwe/pub_mediator#1]
While running `mediator`, the following error is immediately encountered:

```shell
WFCA-00101:wdesk dustinlessard$ mediator
Unhandled exception:
Bad state: expecting only one entry for dependency
#0      DependencyReference.DependencyReference.fromJson (package:pubspec/src/dependency.dart:17)
#1      PubSpec.PubSpec.fromJson.<anonymous closure> (package:pubspec/src/pubspec.dart:99)
#2      JsonParser.mapValues.<anonymous closure> (package:stuff/src/json_utils.dart:122)
#3      YamlNode&MapMixin.forEach (dart:collection/maps.dart:53)
#4      JsonParser.mapValues (package:stuff/src/json_utils.dart:121)
#5      PubSpec.PubSpec.fromJson (package:pubspec/src/pubspec.dart:98)
#6      PubSpec.load.<load_async_body> (package:pubspec/src/pubspec.dart:112)
#7      _RootZone.runUnary (dart:async/zone.dart:1404)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#9      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#10     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#11     _Future._completeWithValue (dart:async/future_impl.dart:477)
#12     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

We have packages that we host on our own pub server.  I noticed that when I comment those out, `mediator` completes.

**Comment by thosakwe** [comment]
Can you run `mediator --verbose` and paste the output?

**Comment by thosakwe** [comment]
Also, I just noticed something that I didn't realize earlier.

I assumed that all "hosted" references look like this:
```yaml
angel_framework: ^1.0.0
```

But it turns out that they can look like this too:
```yaml
transmogrify:
    hosted:
      name: transmogrify
      url: http://your-package-server.com
    version: ^1.4.0
```

So I'll have to add some logic for this. I'm a tad busy today, so I might not be able to get this resolved by tonight, but if you're willing to send in a PR (in a new branch), I would greatly appreciate it.

The API is scarcely documented, so if you have any questions while writing a test, please let me know...

**Comment by dustinlessard-wf** [comment]
I believe the root issue is here : https://github.com/Andersmholmgren/pubspec/issues/1

**Comment by thosakwe** [comment]
I've submitted a PR to patch the root issue: https://github.com/Andersmholmgren/pubspec/pull/4

Just waiting for it to be merged.
