### ISSUE TITLE
Crash with "initial ref transaction called with existing refs"

### ISSUE THREAD

**Issue by MikeMitterer** [thosakwe/pub_mediator#4]
Mediator crashes with

```
Unhandled exception:
git clone git@github.com:MikeMitterer/dart-restrequest.git /Volumes/Daten/DevLocal/DevDart/MobiAd.REST.UI.MDL/samples/mmui_jobedit_inplace/.pub_mediator_temp/restrequest/ exited with code 128: Cloning into '/Volumes/Daten/DevLocal/DevDart/MobiAd.REST.UI.MDL/samples/mmui_jobedit_inplace/.pub_mediator_temp/restrequest'...
fatal: BUG: initial ref transaction called with existing refs

#0      resolvePubspec (package:pub_mediator/src/diagnose.dart:197)
<asynchronous suspension>
#1      identifyRequirements.<anonymous closure> (package:pub_mediator/src/diagnose.dart:281)
#2      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:356)
#3      identifyRequirements (package:pub_mediator/src/diagnose.dart:279)
<asynchronous suspension>
#4      identifyRequirements.<anonymous closure>.<anonymous closure> (package:pub_mediator/src/diagnose.dart:283)
<asynchronous suspension>
#5      _RootZone.runUnary (dart:async/zone.dart:1371)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#7      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#8      _Future._propagateToListeners (dart:async/future_impl.dart:665)
#9      _Future._complete (dart:async/future_impl.dart:468)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:246)
#12     resolvePubspec (package:pub_mediator/src/diagnose.dart:246)
#13     _RootZone.runUnary (dart:async/zone.dart:1371)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#15     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#16     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#17     _Future._complete (dart:async/future_impl.dart:468)
#18     _SyncCompleter.complete (dart:async/future_impl.dart:51)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:246)
#20     PubSpec.load (package:pubspec/src/pubspec.dart:112)
#21     _RootZone.runUnary (dart:async/zone.dart:1371)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#23     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#24     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#25     _Future._completeWithValue (dart:async/future_impl.dart:478)
#26     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:510)
#27     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#28     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#29     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
```

Any ideas?

**Comment by thosakwe** [comment]
Seems like an error with Git, so not 100% sure. Can you paste in your
pubspec?

**Comment by MikeMitterer** [comment]
Hi, I changed quite a few dependencies in the last days. The crash is not reproducible anymore...

I think it was a combination of local-patch-dependencies and git-dependencies...

I ran mediator in `mmui_jobedit_inplace` 
![capturfiles-20171218_014129](https://user-images.githubusercontent.com/116654/34106655-553209d0-e3f9-11e7-948d-19799bb25b94.png)

However - if I run mediator now it gives me
```
✗ Found 5 dependency conflicts:
Found 2 mismatching dependencies on package:webapp_base_signer:
  * mobiad_rest_ui_mdl requires  git://git@github.com:MikeMitterer/webapp.base.signer.git
  * mobiad_rest_ui_mdl->servicefile->restrequest requires  git://git@github.com:MikeMitterer/webapp.base.signer.git
Found 2 mismatching dependencies on package:dart_style:
  * sass_builder->build_runner requires  ^1.0.0
  * mobiad_rest_ui_mdl->webapp_base_ui_mdl->cryptoutils->zengen->source_gen requires  >=0.1.7 <0.3.0
Found 2 mismatching dependencies on package:cli_util:
  * sass_builder->build_runner requires  ^0.1.2
  * mobiad_rest_ui_mdl->webapp_base_ui_mdl->cryptoutils->zengen->source_gen requires  ^0.0.1
Found 2 mismatching dependencies on package:built_collection:
  * sass_builder->build_runner->code_builder requires  ^1.0.0
  * sass_builder->build_runner->code_builder->built_value requires  ^2.0.0
Found 3 mismatching dependencies on package:restrequest:
  * mobiad_rest_ui_mdl->servicefile requires  git://git@github.com:MikeMitterer/dart-restrequest.git
  * mobiad_rest_ui_mdl->webapp_base_ui_mdl->webapp_base_ui requires  git://git@github.com:MikeMitterer/dart-restrequest.git
  * mobiad_rest_ui_mdl->webapp_base_ui_mdl->webapp_base_ui->webapp_base_dart requires  git://git@github.com:MikeMitterer/dart-restrequest.git
Done at 2017-12-18 13:33:49.050865.
```

The `restrequest` dependencies are a bit cumbersome -  they point all to the same GH-repo...

Anyway - mediator was a great help when a searched the sass_builder-problem.
